apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: firstnginx01
  name: firstnginx01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstnginx01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstnginx01
    spec:
      containers:
      - image: localhost:5000/firstnginx01
        name: firstnginx01
        resources: {}
status: {}
